"""init

Revision ID: 4929f8894ec1
Revises: 
Create Date: 2026-02-16 21:10:53.318844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4929f8894ec1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=False),
    sa.Column('total_asistencia', sa.Integer(), nullable=False),
    sa.Column('total_visitantes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_snapshots_id'), 'attendance_snapshots', ['id'], unique=False)
    op.create_table('participation_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=False),
    sa.Column('total_activos', sa.Integer(), nullable=False),
    sa.Column('total_voluntarios', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participation_snapshots_id'), 'participation_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participation_snapshots_id'), table_name='participation_snapshots')
    op.drop_table('participation_snapshots')
    op.drop_index(op.f('ix_attendance_snapshots_id'), table_name='attendance_snapshots')
    op.drop_table('attendance_snapshots')
    # ### end Alembic commands ###
