"""init

Revision ID: 4bc03cfef46a
Revises: 
Create Date: 2026-02-16 21:10:15.198897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4bc03cfef46a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('small_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_small_group_members_id'), 'small_group_members', ['id'], unique=False)
    op.create_table('small_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('leader_person_id', sa.Integer(), nullable=False),
    sa.Column('ministry_id', sa.Integer(), nullable=True),
    sa.Column('meeting_schedule', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_small_groups_id'), 'small_groups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_small_groups_id'), table_name='small_groups')
    op.drop_table('small_groups')
    op.drop_index(op.f('ix_small_group_members_id'), table_name='small_group_members')
    op.drop_table('small_group_members')
    # ### end Alembic commands ###
