"""init

Revision ID: f67a0e7c61ee
Revises: 
Create Date: 2026-02-16 21:09:53.502807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f67a0e7c61ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('responsable_person_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_assignments_id'), 'event_assignments', ['id'], unique=False)
    op.create_table('event_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.String(), nullable=True),
    sa.Column('fin', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_schedules_id'), 'event_schedules', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('ministry_id', sa.Integer(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_event_schedules_id'), table_name='event_schedules')
    op.drop_table('event_schedules')
    op.drop_index(op.f('ix_event_assignments_id'), table_name='event_assignments')
    op.drop_table('event_assignments')
    # ### end Alembic commands ###
