"""init

Revision ID: 099217d88b76
Revises: 
Create Date: 2026-02-16 21:10:02.127652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '099217d88b76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repertoire_songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repertoire_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('tonalidad_override', sa.String(), nullable=True),
    sa.Column('bpm_override', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repertoire_songs_id'), 'repertoire_songs', ['id'], unique=False)
    op.create_table('repertoires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repertoires_id'), 'repertoires', ['id'], unique=False)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('chord_chart_pdf_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_repertoires_id'), table_name='repertoires')
    op.drop_table('repertoires')
    op.drop_index(op.f('ix_repertoire_songs_id'), table_name='repertoire_songs')
    op.drop_table('repertoire_songs')
    # ### end Alembic commands ###
